# Sofle FT: no displays or encoders. Build both halves and a settings reset.
---
include:
  # Left half, no display
  - board: nice_nano//zmk
    shield: sofle_left
    artifact-name: sofle_left_no_display
  # Right half, no display
  - board: nice_nano//zmk
    shield: sofle_right
    artifact-name: sofle_right_no_display
  # Settings reset
  - board: nice_nano//zmk
    shield: settings_reset
